name: Binary Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++ -y

    - name: Compile the binary file
      run: |
        cd cpp
        make

    - name: Upload binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ./cpp/bin